# version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123@pass
  web:
    build: .
    env_file:
      - .env

    command: >
      bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py populate_data data/customer_data.csv data/loan_data.csv &&
      python manage.py runserver 0.0.0.0:8000"


    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db